#!/bin/bash

set -e

resdir=""

if [[ ! -z $1 ]]; then
    resdir=$1
else
    exit 1
fi

resfile=$resdir/$(basename $(pwd)).result.xml

timeout 10800 testkit-lite -f /usr/share/tests/common/common-sanity-suite/testkit.xml --comm tizenlocal -o $resfile

echo -e '\n## Execution script: finished'
